// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/0754cc639a1354a5f52df45c1fd1b0293b90224d/babel-template/babel-template.d.ts
declare module "babel-template" {
    import {BabylonOptions} from 'babylon';
    import * as t from 'babel-types';
    type Node = t.Node;

    // NB: This export doesn't match the handbook example, where `template` is the default export.
    // But it does match the runtime behaviour (at least at the time of this writing). For some reason,
    // babel-template/lib/index.js has this line at the bottom: module.exports = exports["default"];
    export = template;
    function template(code: string, opts?: BabylonOptions): UseTemplate;

    type UseTemplate = (nodes?: {[placeholder: string]: Node}) => Node;
}
